version: "3.7"
services:
  magento2-php-fpm:
    container_name: magento2-php-fpm
    build:
      args:
        user: ${DOCKER_USER}
        uid: ${DOCKER_USER_UID}
        composer_version: ${COMPOSER_VERSION}
        xdebug: ${XDEBUG}
        php_memory_limit: ${PHP_MEMORY_LIMIT}
        xdebug_remote_host: ${XDEBUG_REMOTE_HOST}
      context: ./support/docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
      - 9000:9000
    volumes:
      - ./src:/var/www/html
    depends_on:
      - magento2-database
    networks:
      - magento2-network
  magento2-database:
    container_name: magento2-database
    build:
      context: ./support/docker/mysql
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./support/docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - magento2-network
  magento2-webserver:
    container_name: magento2-webserver
    build:
      context: ./support/docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
      - ./support/docker/nginx/etc/nginx/conf.d:/etc/nginx/conf.d/
    depends_on:
      - magento2-php-fpm
    networks:
      - magento2-network
  magento2-redis:
    container_name: magento2-redis
    build:
      context: ./support/docker/redis
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 6370:6379
    volumes:
      - redis-data:/data
    networks:
      - magento2-network
  magento2-varnish:
    container_name: magento2-varnish
    build:
      context: ./support/docker/varnish
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
    - "80:6081"
    - "6085:6085"
    volumes:
      - varnish-data:/data
    networks:
      - magento2-network

  magento2-elasticsearch:
    container_name: magento2-elasticsearch
    build: ./support/docker/elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_USER=${ELASTICSEARCH_USERNAME}
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - magento2-network

networks:
  magento2-network:
    driver: bridge
volumes:
  redis-data:
  varnish-data:
  elasticsearch-data: