version: "3.7"
services:
  magento2-php-fpm:
    container_name: magento2-php-fpm
    build:
      args:
        user: ${DOCKER_USER}
        uid: ${DOCKER_USER_UID}
        composer_version: ${COMPOSER_VERSION}
      context: ./support/docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    depends_on:
      - magento2-database
    networks:
      - magento2-network
  magento2-database:
    container_name: magento2-database
    build:
      context: ./support/docker/mysql
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./support/docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - magento2-network

  magento2-webserver:
    container_name: magento2-webserver
    build:
      context: ./support/docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./support/docker/nginx/etc/nginx/conf.d:/etc/nginx/conf.d/
    depends_on:
      - magento2-php-fpm
    networks:
      - magento2-network

  magento2-elasticsearch:
    container_name: magento2-elasticsearch
    build: ./support/docker/elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_USER=${ELASTICSEARCH_USERNAME}
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - magento2-network

networks:
  magento2-network:
    driver: bridge
volumes:
  elasticsearch-data:
    driver: local
